#!/usr/bin/env node
// Regenerates every icon from build/haven-logomark.svg. Run it after the
// artwork changes and commit the results — the outputs are checked in so a
// plain `npm run dist` needs no image tooling:
//
//   node scripts/make-icons.mjs
//
// Outputs:
//   build/icon.ico   Windows executable + NSIS installer (multi-size)
//   build/icon.png   1024px master; electron-builder derives the mac .icns
//                    and the Linux AppImage icon from it
//   tray-icons.generated.js  base64 tray glyphs, imported by tray-icon.js
//
// The wordmark logo (build/haven-logo-vertical.svg) is deliberately unused:
// "HAVEN" is unreadable once the icon is scaled to 16px.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compose, coverage, encodeIco, encodePng, fitted, parseSvg, roundedRect } from "./svg-raster.mjs";

const appDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const logomark = parseSvg(readFileSync(join(appDir, "build", "haven-logomark.svg"), "utf8"));

const TILE_COLOR = [0x11, 0x14, 0x18]; // near-black, so the white glyph carries the icon
const TRAY_GLYPH_SCALE = 0.94; // tray glyphs are bare, so they fill their box
const STOPPED_ALPHA = 0.45; // dimmed glyph = proxy not running

// Padding and corner rounding are fractions of the icon side, so a 16px entry
// would put the glyph in ~10px and lose the H. Small entries trade the airy
// large-icon proportions for legibility: bigger glyph, tighter corners.
function proportions(size) {
  if (size <= 24) return { glyph: 0.84, radius: 0.14 };
  if (size <= 48) return { glyph: 0.74, radius: 0.17 };
  return { glyph: 0.62, radius: 0.2 };
}

/** App icon: white logomark on a rounded dark tile. */
function appIcon(size) {
  const { glyph, radius } = proportions(size);
  const rgba = Buffer.alloc(size * size * 4);
  compose(rgba, coverage([roundedRect(0, 0, size, size, size * radius)], size, size), TILE_COLOR);
  compose(rgba, coverage(fitted(logomark, size, glyph), size, size), [0xff, 0xff, 0xff]);
  return rgba;
}

/** Tray glyph: bare logomark, no tile, so the shell's own background shows. */
function trayGlyph(size, color, alpha) {
  const rgba = Buffer.alloc(size * size * 4);
  compose(rgba, coverage(fitted(logomark, size, TRAY_GLYPH_SCALE), size, size), color, alpha);
  return encodePng(size, size, rgba).toString("base64");
}

const ICO_SIZES = [16, 24, 32, 48, 64, 128, 256];
const icoPath = join(appDir, "build", "icon.ico");
writeFileSync(icoPath, encodeIco(ICO_SIZES.map((size) => ({ size, rgba: appIcon(size) }))));
console.log(`[make-icons] ${icoPath} (${ICO_SIZES.join(", ")})`);

const pngPath = join(appDir, "build", "icon.png");
writeFileSync(pngPath, encodePng(1024, 1024, appIcon(1024)));
console.log(`[make-icons] ${pngPath} (1024)`);

// Two colours because no platform tells us the tray background directly:
// macOS tints the template image itself, and on Windows/Linux tray-icon.js
// picks by nativeTheme.
const WHITE = [0xff, 0xff, 0xff];
const BLACK = [0x00, 0x00, 0x00];
const trayIcons = {
  whiteRunning: { 1: trayGlyph(16, WHITE, 1), 2: trayGlyph(32, WHITE, 1) },
  whiteStopped: { 1: trayGlyph(16, WHITE, STOPPED_ALPHA), 2: trayGlyph(32, WHITE, STOPPED_ALPHA) },
  blackRunning: { 1: trayGlyph(16, BLACK, 1), 2: trayGlyph(32, BLACK, 1) },
  blackStopped: { 1: trayGlyph(16, BLACK, STOPPED_ALPHA), 2: trayGlyph(32, BLACK, STOPPED_ALPHA) },
};

const trayPath = join(appDir, "tray-icons.generated.js");
writeFileSync(
  trayPath,
  `// GENERATED by scripts/make-icons.mjs from build/haven-logomark.svg — do not edit.\n` +
    `// Base64 PNG tray glyphs, keyed by variant then by scale factor (1 = 16px, 2 = 32px).\n` +
    `export const TRAY_ICONS = ${JSON.stringify(trayIcons, null, 2)};\n`,
);
console.log(`[make-icons] ${trayPath}`);
